example.ai_study_notes:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: app_test
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 3000
    ttl: 300

ai:
  ark:
    base-url: https://ark.cn-beijing.volces.com/api/coding/v3
    api-key: <your ARK_API_KEY>  # @secret ARK_API_KEY
    doc-parser: deepseek-v4-flash
    requirement-analysis: doubao-seed-2.0-pro
    question-generation: deepseek-v4-flash
    test-case-generation: doubao-seed-code
    result-analysis: deepseek-v4-pro

task:
  scheduler:
    enable:
      accessUserInfo: false   #控制定时任务开启
      collectECSMetricInfo: true
  cron:
    accessUserInfo: 0 */5 * * * *
    collectESCMetricInfo: 10000
  scope: